name: "CD Develop - Pipeline (Fronted)"

on:
  push:
    branches: [ "develop" ]
    # Solo se ejecuta si hay cambios en la carpeta de la APP
    paths:
      - 'app/**'
      - '.github/workflows/cd-develop.yml'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  # 1. Mandar a llamar al flujo de seguridad
  ejecutar-seguridad:
    name: "Validaciones de Seguridad"
    uses: ./.github/workflows/security-scan.yml

  # 2. Si el escaneo es exitoso, proceder con el despliegue del API
  desplegar-backend:
    name: "Despliegue del Fronted"
    needs: ejecutar-seguridad
    uses: ./.github/workflows/deploy-frontend.yml